"""modifying tables

Revision ID: 44a678c44a2c
Revises: f38e3864584d
Create Date: 2026-07-14 15:52:41.438214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a678c44a2c'
down_revision: Union[str, Sequence[str], None] = 'f38e3864584d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('size', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
