"""modifying tables

Revision ID: 5f9e9b822da3
Revises: cc52c273bf1c
Create Date: 2026-07-13 17:59:44.412728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9e9b822da3'
down_revision: Union[str, Sequence[str], None] = 'cc52c273bf1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_product'), 'products', type_='unique')
    op.create_unique_constraint('uq_product', 'products', ['name', 'brand', 'size'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product', 'products', type_='unique')
    op.create_unique_constraint(op.f('uq_product'), 'products', ['name', 'brand', 'description', 'size'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
