"""updated shopping list schema renamed is_count to checked_count

Revision ID: 6c11a88a3942
Revises: adfa4a39a3b2
Create Date: 2026-07-22 20:39:57.903682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c11a88a3942'
down_revision: Union[str, Sequence[str], None] = 'adfa4a39a3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
