"""removed null from product id in shoppiung list table

Revision ID: adfa4a39a3b2
Revises: e034305dd453
Create Date: 2026-07-22 16:43:56.405873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfa4a39a3b2'
down_revision: Union[str, Sequence[str], None] = 'e034305dd453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
