"""added cascade delete oni shoppinglistitem table

Revision ID: bbd0b3261b2e
Revises: j6e1f2a3b4c5
Create Date: 2026-08-10 19:24:49.382644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd0b3261b2e'
down_revision: Union[str, Sequence[str], None] = 'j6e1f2a3b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('shopping_list_items_shopping_list_id_fkey'), 'shopping_list_items', type_='foreignkey')
    op.create_foreign_key(None, 'shopping_list_items', 'shopping_lists', ['shopping_list_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_list_items', type_='foreignkey')
    op.create_foreign_key(op.f('shopping_list_items_shopping_list_id_fkey'), 'shopping_list_items', 'shopping_lists', ['shopping_list_id'], ['id'])
    # ### end Alembic commands ###
