"""create products table

Revision ID: c1d78e637e98
Revises: 
Create Date: 2026-07-08 18:26:26.236359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d78e637e98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('store', sa.String(length=120), nullable=True),
    sa.Column('barcode', sa.String(length=80), nullable=True),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('size', sa.String(length=80), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
