"""modifying tables

Revision ID: cc52c273bf1c
Revises: 2ef742e9af0a
Create Date: 2026-07-13 17:44:52.222598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc52c273bf1c'
down_revision: Union[str, Sequence[str], None] = '2ef742e9af0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(length=120), nullable=False))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=False))
    op.alter_column('products', 'size',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.create_unique_constraint('uq_product', 'products', ['name', 'brand', 'description', 'size'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product', 'products', type_='unique')
    op.alter_column('products', 'size',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_column('products', 'description')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
