"""modifying tables

Revision ID: e032b0b790ef
Revises: 5f9e9b822da3
Create Date: 2026-07-14 00:40:26.744152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e032b0b790ef'
down_revision: Union[str, Sequence[str], None] = '5f9e9b822da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_aliases')
    op.drop_column('categories', 'sort_order')
    op.alter_column('grocery_list_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('grocery_list_items', 'updated_at')
    op.drop_column('grocery_list_items', 'created_at')
    op.drop_column('grocery_lists', 'status')
    op.drop_column('grocery_lists', 'completed_at')
    op.drop_column('grocery_lists', 'updated_at')
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_product'), 'products', type_='unique')
    op.create_unique_constraint('uq_product', 'products', ['name', 'size'])
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'description')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint('uq_product', 'products', type_='unique')
    op.create_unique_constraint(op.f('uq_product'), 'products', ['name', 'brand', 'size'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'category_id')
    op.add_column('grocery_lists', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('grocery_lists', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('grocery_lists', sa.Column('status', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('grocery_list_items', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('grocery_list_items', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('grocery_list_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('categories', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('product_aliases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_aliases_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_aliases_pkey')),
    sa.UniqueConstraint('alias', name=op.f('product_aliases_alias_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('product_id', 'alias', 'language', name=op.f('uq_product_alias'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
