"""added unique contraint on shopping list item table

Revision ID: e034305dd453
Revises: 04b27a9ed9ae
Create Date: 2026-07-22 16:17:43.450660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e034305dd453'
down_revision: Union[str, Sequence[str], None] = '04b27a9ed9ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_shopping_list_product', 'shopping_list_items', ['shopping_list_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_shopping_list_product', 'shopping_list_items', type_='unique')
    # ### end Alembic commands ###
