"""modifying tables

Revision ID: e8594ab6e980
Revises: e032b0b790ef
Create Date: 2026-07-14 14:33:06.489916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8594ab6e980'
down_revision: Union[str, Sequence[str], None] = 'e032b0b790ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_product'), 'products', type_='unique')
    op.create_unique_constraint(None, 'products', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.create_unique_constraint(op.f('uq_product'), 'products', ['name', 'size'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
