"""modifying tables

Revision ID: f38e3864584d
Revises: e8594ab6e980
Create Date: 2026-07-14 15:46:36.385969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38e3864584d'
down_revision: Union[str, Sequence[str], None] = 'e8594ab6e980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=180),
               existing_nullable=False)
    op.alter_column('products', 'size',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'size',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=180),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
